### ISSUE TITLE
Write package vignette

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BSgenomeForge#24]
@kakopo 

**Some general information about vignettes:**

- A vignette is a document that introduces a package and illustrates its typical use. It can be very short (e.g. less than 2 pages) for a simple package like **BSgenomeForge** that has only 2 easy -to-use functions to accomplish a very specific task, or quite long if the vignette needs to describe a complex workflow (e.g. the **DESeq2** package, see the "Analyzing RNA-seq data with DESeq2" vignette on the package landing page [here](https://bioconductor.org/packages/DESeq2)).

- Every Bioconductor package is required to contain at least one vignette.

- It's usually one of the first things that users look at before starting to use a package. Based on what they see in the vignette, they will decide whether the package is what they need for the task that they're trying to accomplish or not.

- A vignette is typically a dynamic document that contains chunks of R code intertwined with text. The latter provides a narrative and context for the R commands shown in the code chunks.

- The code chunks will get automatically executed when the vignette is rendered (i.e. turned into an HTML or PDF document). More on this below.

- The source file of a vignette should be an R Markdown file (`.Rmd` extension). Even though other formats are possible (e.g. Sweave, `.Rnw` extension), the Bioconductor project has a strong preference for Rmd vignettes (as you and @BerylKanali know :wink: ).

- The standard location for package vignettes is the `vignettes/` folder. The **BSgenomeForge** package does not have this folder yet, so you'll need to create it.

- Then add the `UsingBSgenomeForge.Rmd` file there. Don't forget to `git add vignettes/UsingBSgenomeForge.Rmd` after you put the file there.

- You can render the vignette anytime with `rmarkdown::render("vignettes/UsingBSgenomeForge.Rmd")` (from R). This will produce the HTML vignette that you should then be able to open in a browser. Maybe there's a button in Rstudio for doing that too, I don't know.

- Note that `R CMD build` will also produce the HTML vignette and place it in the `inst/doc/` folder of the _package source tarball_. When people use this tarball to install the package, then they'll be able to access the HTML vignette with `browseVignettes("BSgenomeForge")`.

- See https://contributions.bioconductor.org/docs.html#docs for more information about vignettes.

**Proposed outline for the `UsingBSgenomeForge.Rmd` vignette:**

(This is only a suggestion, feel free to deviate.)

- Title: How to use the **BSgenomeForge** package to forge a BSgenome data package

- Section 1: Introduction. Explain what _BSgenome data packages_ are (it's ok to copy/paste [this](https://github.com/Bioconductor/BSgenomeForge#readme)), and what they are typically used for (like you've done in your blogs). What's the purpose of the **BSgenomeForge** package. Quickly mention the old way of forging them (and its lack of convenience). List the 2 main functions in **BSgenomeForge**.

- Section 2: One (or maybe 2) examples with `forgeBSgenomeDataPkgFromNCBI()`. Suggest `?forgeBSgenomeDataPkgFromNCBI` for more information.

- Section 3: One (or maybe 2) examples with `forgeBSgenomeDataPkgFromUCSC()`. Suggest `?forgeBSgenomeDataPkgFromUCSC` for more information.

- Section 4: The final steps. Show how to build the _package source tarball_ for the packages created in the above sections, how to install this tarball, and how to start using it. The code chunks in the very last steps (installation and use) should not be evaluated though because the code in vignettes, examples, or unit tests, is not allowed to install packages.

- Section 5: `sessionInfo()`

Nothing really fancy or truly original :expressionless: 

Let me know if you have questions.

**Comment by kakopo** [comment]
Hi Hervé, please check out my latest pull request addressing this issue. It is not quite perfect yet, but I would appreciate your feedback. Thank you.

**Comment by hpages** [comment]
Let's use "main" and not "major" for 2 `forgeBSgenomeDataPkgFrom*()` functions.
 
The two `forgeBSgenomeDataPkgFromNCBI()` examples are too similar. Yes one is for a registered assembly and the other one is for an unregistered assembly, but in both cases the way to call the function is exactly the same, so the reader might wonder why being registered or not matters. It would be more interesting for the user to see an example where the circular sequences need to be specified.

The examples also lack context. Maybe mention the NCBI page for a given assembly where one usually goes first to get the exact assembly accession and assembly name to use in the call?

**Comment by hpages** [comment]
Also look at `GenomeInfoDb/vignettes/Accept-organism-for-GenomeInfoDb.Rmd` or `SummarizedExperiment/vignettes/SummarizedExperiment.Rmd` for an example of what to put in the header. In particular we should use `BiocStyle::html_document:` instead of just `html_document:`. I don't think we need the `editor_options:` block. Thanks!

**Comment by kakopo** [comment]
Hi @hpages, I was able to solve the issue with @BerylKanali's help. Please take a look at the latest commit and let me know what you think. Thank you.

**Comment by hpages** [comment]
Thanks.

Why aren't the code chunks evaluated? (except for the `sessionInfo` chunk, they use `eval = FALSE`)

Also this:

> Suggest ?forgeBSgenomeDataPkgFromNCBI for more information.

The commands used for the final steps (e.g. `R CMD build <pkgdir>`) should be displayed as code (this is not R code but it's still code, not text). So it would be nice to put them in code chunks. We just use the usual markdown syntax for that e.g.:

    ```
    R CMD build <pkgdir>
    ```

BTW I would suggest that you make it clear in the text that those commands need to be executed at the command line (i.e. in a Linux/Unix terminal or Windows PowerShell terminal).

However, note that it's possible to perform those same operations from R with `devtools::build()`, `devtools::check()`, and `devtools::install()`, so that's something you could use here if you want to explore that. In this case, the code chunks would need to be R code chunks (i.e. start with ` ```{r} `), and the last one (`devtools::install`) would need to use `eval=FALSE` because as mentioned earlier the code in vignettes, examples, or unit tests, is not allowed to install packages. Also the **devtools** package would need to be added to the `Suggests:` field because it's used in the vignette.

H.

**Comment by kakopo** [comment]
Hi Hervé, I have updated the code to reflect these changes. Please take a look at the latest commits in the PR and let me know what you think. Thank you!

**Comment by hpages** [comment]
Great.

There are a few more things, sorry.

- Please check the HTML vignette. Some commands in the vignette (e.g. `library(BSgenomeForge)` or `devtools::check()`) generate long and ugly output that will distract the reader. You can avoid this by putting `library(BSgenomeForge)` in its own code chunk and by hidding the output with ` ```{r, results="hide"}`. For `devtools::check()`, see below.

- As discussed during our call, I don't know why calling `devtools::check()` on the source tarball did not work for you, I don't use **devtools** myself. But the very first thing you _absolutely_ want to do when a function is causing you trouble is check its man page. Only after you've done that and still can't figure out what the problem is, then try to reach out for help.

  In this case the man page says:

    ```
     ‘check()’ automatically builds and checks a source package, using
     all known best practices. ‘check_built()’ checks an already-built
     package.
    ```

  So if you've already built the source tarball, it seems that you want to use `devtools::check_built()` instead of `devtools::check()`.

- Note that the `devtools::check_built()` (or `devtools::check()`) call takes quite a long time (3-4 minutes on my laptop) so this is a situation where it's probably ok to use `eval=FALSE`. Furthermore, note that running `R CMD check` on a package is something that is important to do as part of the typical workflow of _developing_ a package. However, in this case, the BSgenome data package got automatically generated, and the end user would expect that the tool they used for doing that (`forgeBSgenomeDataPkgFromNCBI()`) would generate valid packages (they trust that we're not providing broken tools :wink:). So running `R CMD check` here is still a good idea, but not as important as in the context of _developing_ a package.

- Note that by default R code chunks are evaluated so you don't need to specify `eval=TRUE`.

- Using the **BiocStyle** package for the rendering of the vignette provides consitent styling across all Bioconductor vignettes. For package names in the text, the recommendation is to use `` `r Biocpkg("BSgenomeForge")` `` for a Bioconductor package and `` `r Biocpkg("devtools")` `` for a CRAN package. This will automatically create the correct link to the package landing page when the vignette is rendered, so you don't need to do something like `[BSgenome](https://github.com/Bioconductor/BSgenome)`, just use `` `r Biocpkg("BSgenome")` `` instead.

- Is it really "three" here?
    ```
    Assembly ASM836960v1 contains three circular sequence, “MT” which must specified as shown in the example below:
    ```
  Also "be" is missing between "must" and "specified".

Thanks

**Comment by kakopo** [comment]
Thanks for the feedback. I've improved the code in the vignette and updated the PR. I did not fully understand this bit:

>  Furthermore, note that running R CMD check on a package is something that is important to do as part of the typical workflow of developing a package. However, in this case, the BSgenome data package got automatically generated, and the end user would expect that the tool they used for doing that (forgeBSgenomeDataPkgFromNCBI()) would generate valid packages (they trust that we're not providing broken tools wink). So running R CMD check here is still a good idea, but not as important as in the context of developing a package.

so I used `devtools::check_built()` after `devtools::build()` rather than simply using `devtools::check()` to imitate the behaviour of `R CMD build` and `R CMD check`. 

`{r, results="hide"}` did not seem to work for the `library(BSgenomeForge)` chunk, so I used `{r, message=FALSE}` instead. I hope this is alright. 

Let me know if this is good, thanks!

**Comment by hpages** [comment]
Please make sure to use `` `r Biocpkg("pkgname")` `` for _all_ Bioconductor packages. Looks like you missed a few (e.g. **BSgenome.Hsapiens.UCSC.hg19** and **BSgenome**).

For **devtools**, sorry I made a typo in my previous comment, but you need to use `` `r CRANpkg(...)` `` instead of `` `r Biocpkg(...)` `` (see `?Biocpkg` in the **BiocStyle** package for the details). Right now the link for **devtools** that you get in the HTML vignette doesn't work.

I woud suggest that you put the simpler example (i.e. the example with no circular sequences) first. The other example is more complicated. In particular figuring out what the circular sequences are is not obvious and it would be worth explaining that part.

As you can see in the HTML vignette, numbering the examples as you did has the effect of indenting the corresponding paragraphs with respect to the code chunks and the rest of the text. Do you like how this looks?

No need to use `message=FALSE` or `results='hide'` everywhere. I was suggesting to hide messages or results only when they are problematic and/or not informative at all. For example it makes sense to do it for `library(BSgenomeForge)` which produces long and noisy output. But in the case if our main functions, the output they produce is useful and of interest to the user so we shouldn't try to hide it. 

Thanks

**Comment by hpages** [comment]
> I did not fully understand this bit:
>
>>  Furthermore, note that running R CMD check on a package is something that is important to do as part of the typical workflow of developing a package. However, in this case, the BSgenome data package got automatically generated, and the end user would expect that the tool they used for doing that (forgeBSgenomeDataPkgFromNCBI()) would generate valid packages (they trust that we're not providing broken tools :wink:). So running R CMD check here is still a good idea, but not as important as in the context of developing a package.

I was trying to make the distinction between a package that is being _developed_ (like **GenomeInfoDb** or **GenomeInfoDb**) and a package that is _automatically generated_ (like the packages produced by `forgeBSgenomeDataPkgFromNCBI()`). For the former, running `R CMD check` on the package is important and should be done by the developer everytime they make changes to the package (and before they push the changes). For the latter, running `R CMD check` is still a good idea but probably not as important.

**Comment by kakopo** [comment]
> I was trying to make the distinction between a package that is being developed (like GenomeInfoDb or BSgenomeForge) and a package that is automatically generated (like the packages produced by forgeBSgenomeDataPkgFromNCBI()). For the former, running R CMD check on the package is important and should be done by the developer everytime they make changes to the package (and before they push the changes). For the latter, running R CMD check is still a good idea but probably not as important

Thank you for the explanation, I get it now! I've edited the code and I hope it is much better now. Please take a look, thanks.

**Comment by hpages** [comment]
You still have:

    the [BSgenome](https://bioconductor.org/packages/BSgenome/) software package

You need to use `` `r Biocpkg(...)` ``.

OTOH you should not use this for "`` `r Biocpkg(BSgenome)` `` data packages", because those are _data_ packages. Using `` `r Biocpkg(...)` `` here creates a link to the BSgenome _software_ package which is something different. More precisely, when we write "BSgenome data package" we are referring to a type of data package, not to a particular package, so we can't really put a link to a particular package. Hope this makes sense.

**Comment by kakopo** [comment]
Sorry, I did not catch that. I've made the proper adjustment, thank you.

**Comment by hpages** [comment]
Thanks. PR #30 is merged. Don't forget to resync your fork.

Now let's get the package ready for submission to Bioconductor. See issue #29. Thanks!

Note that I still need to finish working on `forgeBSgenomeForgePkgFromUCSC()` but that should not stop you from getting the package ready for submission.

Let me know in issue #29 if you have questions.
